# Generated by Django 3.2.6 on 2021-08-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPIapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'catergories'},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
